stacks: ./data/stacks
templates: ./data/templates
terraform_commands: ./data/scripts
stack_volume: not_defined

terraform_image: jetbrainsinfra/terraform

expire_day: 5
notify_day: 4
web_address: 127.0.0.1:8080



security:
  oauth2:
    client:
      clientId: c7442f0f-d891-4163-a9bd-698016427c11
      clientSecret: WL8jAmjsRFut
      accessTokenUri: https://hub-staging.labs.intellij.net/api/rest/oauth2/token
      userAuthorizationUri: https://hub-staging.labs.intellij.net/api/rest/oauth2/auth
      scope:
        - openid
        - email
    resource:
      userInfoUri: https://hub-staging.labs.intellij.net/api/rest/oauth2/userinfo
spring:
  data:
    mongodb:
      host: localhost
      port: 27017
  mail:
    host: smtp.gmail.com
    port: 587
    properties:
      mail:
        smtp:
          starttls:
            enable: true
            required: true
          auth: true
          connectiontimeout: 5000
          timeout: 5000
          writetimeout: 5000
    username: ${EMAIL_LOGIN}
    password: ${EMAIL_PASSWORD}
