stacks: ./data/stacks
templates: ./data/templates
terraform_commands: ./data/scripts-docker

expire_day: ${EXPIRE_DAY}
notify_day: ${NOTIFY_DAY}
web_address: ${WEB_ADDRESS}
terraform_image: ${TERRAFORM_IMAGE}

security:
  oauth2:
    client:
      clientId: ${OAUTH_CLIENT_ID}
      clientSecret: ${OAUTH2_SECRET}
      accessTokenUri: ${OAUTH_ACCESS_TOKEN_URI}
      userAuthorizationUri: ${OAUTH_AUTHRIZATION_URI}
      scope:
        - openid
        - email
    resource:
      userInfoUri: ${OAUTH_USER_INFO_URI}
spring:
  data:
    mongodb:
      host: ${DB_HOST}
      port: ${DB_PORT}
  mail:
    host: ${EMAIL_HOST}
    port: ${EMAIL_PORT}
    properties:
      mail:
        smtp:
          starttls:
            enable: ${EMAIL_TLS_ENABLE}
            required: ${EMAIL_TLS_REQUIRED}
          auth:  ${EMAIL_AUTH_ENABLE}
          connectiontimeout: 5000
          timeout: 5000
          writetimeout: 5000
    username: ${EMAIL_LOGIN}
    password: ${EMAIL_PASSWORD}